%YAML:1.0


# Waypoint matrix
waypointMatrix: !!opencv-matrix
  rows: 3   # The number of waypoints
  cols: 9   # p v a
  dt: d
  data:
    [
      0,      0,      1.58,       0, 0, 0,      0, 0, 0,
      4,    0,   1.58,       0, 0, 0,          -1.5,0, 0,
      0,    0,  1.58,       0, 0, 0,      0, 0, 0
      #        5,      0,      0.58,       0, 0, 0,      0, 0, 0
    ]
    # if you set v and a = -1, this point will be regarded as waypoint in one path.
    # position      velocity      Acceleration
#    [
#        0,      0,      0.58,       0, 0, 0,      0, 0, 0,
#        1.05,   1.03,   0.58,       1, -1, 0,     1, 1, 0,
#        1.5,    -0.76,  0.58,       1, 1, 0,      0, 0, 0,
#        5,      0,      0.58,       0, 0, 0,      0, 0, 0
#    ]

